language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - build-tools-28.0.3
  - android-28
  - platform-tools
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra
  - addon

  licenses:
  - android-sdk-license-.+
script: ./gradlew clean build
