language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - tools
  - build-tools-28.0.3
  - android-28
  - platform-tools
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra
  - addon
  licenses:
  - android-sdk-license-.+
script: "./gradlew clean build"

env:
  matrix:
  - secure: 4nJv/ptZWNgJxXspdEM8JCQ6ZNjN3exlBY8S5xkhcIkOZwvmIFreX75wjfSeCUp+G8Q0lmiUN88uC0RvZP+Tg/EBJqIvB4oFr2wJieUrukJbOdrXlDI/2FMqPjAX3mU2lbmEWdmzarSRmiUWgfmZhqs8QssOZfZWTVUJx1ac85iBjjQxX2VtJZW+fbEfaDoz68zcIXF9dMHJvgdQmAmRkzIIshoiVWRb2UFJmE8TgF6/15aUuyMy1RB7aWzgJl5fK9Vn01Bn2K9Brgd42p6okJU188J857BAyJEZENyzUo45q0K8HUtF7H+NJwPoWLmolPtFKxufKv668YxAY7n5tcOqglD0oFKpRbfAxw+Ds+EGk7gAYvV9b7J9FZuuS/58h5Fydgvlbmz/FuOXtQWaogc0VoUlcz51vsgzX1M6Z7fJwzXXT2nAyRF1qQAAH8HkrVe1+IeEcM3ri2iu0SDPtfo0B6w30MxAxgg5gvyPhdPj/6jjfdktz0FsmDGEXmdEJDP9nDgLqNfMPbc1MYzhukLiHniPaQ66F3NLiRIBPw4knTZbvI8UtwB6/rf9PqHZkUGp+BVrXgb9Djl8xoh1aw1jEA8rHLZA8nAasnYA7lowUBj0ENW+MUwDHibn2B2uxQlaWULyVm7bXWd8OYl8miaLRs+2ljFl4H/ZPb+6LSo=
  - secure: z61JxAT+gQqEN9qpMQqRBYE2n1BkTHAA0mJAawVJ++sEpjdu+d+W2UbIOn1B+hl/qOtEwF+f4FCXlcUbiKDL7Cp87CzwmFT0A3Ec1gCqOc9mrrQu4msW6kVCYO5xEsXtCUa9suenMCsWWBdf7ZfRBGopdeAtpBWEfh6e2RyUd0E+uMiI9IeeEEZjCFjm9cECj+QH2HlqTmEWP2DcKXpE88n/NtJyBQdSRRrK3YRB9NofNJ6XqfAzeqBmqmx2eQ/vaO/zLWPuNjVXYRRXlyyPR6RxfWyx6AztmxNPbtadTov42QckLYXFYi5doW3z0mNgL37NLhnyjvpXJM4dnP6ooWZoSjQq/nd9v0iYrOfTzYLWkdZObiW1L7hU7A2r96Dby2bSzUoVqnNvtGSSOuk+jWthpnWe+dtP8u7H87LoIgin1TcoMkCNGjGPa49dCI5LZdnxzSokYd0UIF36AEE8CiInQ6GgNn6VZNy6jfBs5CTCDgI4ppklUgIjPAL1Y6t/PRlKXa2gRo9VSKwbmlSrI55r3Yqh0UugdUHq4MNFvK9Qi/Vs+biSVykqNXDvPgahb1dD2p2P08tVrsiT8EQTbqPGYumyFD57bvrJAXdHixLxOHNC2y29TvWZqnx7E7dXXJpkzzyzdxqWSGCqwqzPsU8woD3og82m3njB2WJzUz8=
